version: "3.8"
services:
  rki-api:
    build: .
    # image: docker.pkg.github.com/marlon360/rki-covid-api/rki-server:latest
    ports:
      - "8080:3000"
    environment:
      - DATABASE_USER
      - DATABASE_PASSWORD
      - DATABASE_NAME
    volumes:
      - ./cache:/usr/src/app/cache