#!/bin/bash

# Get architecture from Dockerfile.arch filename
BUILD_ARCH=$(echo "${DOCKERFILE_PATH}" | cut -d '.' -f 2)

# For amd64 filename is Dockerfile
[ "${BUILD_ARCH}" == "Dockerfile" ] && \
    { echo 'qemu-user-static: Download not required for current arch'; exit 0; }

case ${BUILD_ARCH} in
    amd64   ) QEMU_ARCH="x86_64" ;;
    arm32v6 ) QEMU_ARCH="arm" ;;
    arm32v7 ) QEMU_ARCH="arm" ;;
    arm64v8 ) QEMU_ARCH="aarch64" ;
 esac

QEMU_USER_STATIC_DOWNLOAD_URL="https://github.com/multiarch/qemu-user-static/releases/download"
QEMU_USER_STATIC_LATEST_TAG=$(curl -s https://api.github.com/repos/multiarch/qemu-user-static/tags \
    | grep 'name.*v[0-9]' \
    | head -n 1 \
    | cut -d '"' -f 4)

curl -SL "${QEMU_USER_STATIC_DOWNLOAD_URL}/${QEMU_USER_STATIC_LATEST_TAG}/x86_64_qemu-${QEMU_ARCH}-static.tar.gz" \
    | tar xzv
