name: Code style
on:
  push:
    branches:
      - "master"
      - "develop"
      - "v2"
      - "v2-proxy"
  pull_request:
    branches:
      - "master"
      - "develop"
      - "v2"
      - "v2-proxy"

jobs:
  code_style:
    name: Check code style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo Files
        uses: actions/checkout@v2
      - name: Download and setup npm
        uses: actions/setup-node@v2
      - name: Install devDependencies
        run: npm install --only=dev
      - name: Check code style
        run: npm run lint
