name: Code style
on:
  push:
    branches:
      - "mein-v2"
  pull_request:
    branches:
      - "mein-v2"

jobs:
  code_style:
    name: Check code style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo Files
        uses: actions/checkout@v2
      - name: Download and setup npm
        uses: actions/setup-node@v2
      - name: Install devDependencies
        run: npm install --only=dev
      - name: Check code style
        run: npm run lint
